### ISSUE TITLE
Is it possible to configure realms with connection profiles for wifi hotspot for coovachilli?

### ISSUE THREAD

**Issue by noirwave** [vzakharchenko/keycloak-radius-plugin#164]
There is a radius sever Radiusdesk, where i can configure profiles for connection restriction.
But it has own database.
We want to use KeyCloak for SSO and this plugin for radius features.
Is it possible to configure radius server like in this post?
https://gremaudpi.emf-informatique.ch/how-to-build-a-captive-portal-with-radiusdesk-and-coova-chilli-on-raspberry-pi-running-openwrt/

**Comment by vzakharchenko** [comment]
You can try updating coovachilli config like this
```
radiusserver1=<Keycloak address>
radiussecret=<Shared Secret>
```
or you can use radsec https://coova.github.io/CoovaChilli/RadSec/
