### ISSUE TITLE
Client Mappers tab not rendering properly

### ISSUE THREAD

**Issue by keyhana** [vzakharchenko/keycloak-radius-plugin#278]
Hello,
I have an issue with the radius theme. When I try to open the Mappers tab or the Installation tab of a client, it does not render properly and shows this page.
I'm not sure if this is intended, if not I can submit a PR to disable those tabs for radius-protocol clients.

![Keycloak Admin Console](https://user-images.githubusercontent.com/10401843/105629278-481da480-5e57-11eb-9e06-7e2e88d0e3e4.png)

**Comment by vzakharchenko** [comment]
Hi @keyhana, In theme is only interested  authorization.

 Please, create a PR, If you can remove the Mappers and installation tab.
Thanks
