### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils

### ISSUE THREAD

**Issue by TheSDTM** [vzakharchenko/keycloak-radius-plugin#313]
**Describe the bug**
Hello. I faced an issue when the request doesn't contain a realm name. Please, see the log below.
Everything is OK when I send the realm name explicitly, but Unifi doesn't support setting a realm name.

**To Reproduce**
Use an example with a default realm name

**Expected behavior**
Get SUCCESS status

**Desktop (please complete the following information):**
 - Keycloak-radius-plugin Docker container v 1.3.5

**Additional context**
Logs:
`15:21:01,456 ERROR [stderr] (pool-19-thread-1) Exception in thread "pool-19-thread-1" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
15:21:01,457 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.RadiusHelper.getRealmFromUserName(RadiusHelper.java:190)
15:21:01,457 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.RadiusHelper.getRealm(RadiusHelper.java:214)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.handlers.protocols.AbstractAuthProtocol.isValid(AbstractAuthProtocol.java:90)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.handlers.AuthHandler.channelRead0(AuthHandler.java:102)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.handlers.AuthHandler.lambda$channelReadRadius$0(AuthHandler.java:120)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at org.keycloak.keycloak-server-spi-private@12.0.4//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:228)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at keycloak.plugins.radius//com.github.vzakharchenko.radius.radius.handlers.AuthHandler.channelReadRadius(AuthHandler.java:118)
15:21:01,458 ERROR [stderr] (pool-19-thread-1)  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
15:21:01,459 ERROR [stderr] (pool-19-thread-1) Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils from [Module "keycloak.plugins.radius" from local module loader @13d9b21f (finder: local module finder @2826f61 (roots: /opt/jboss/keycloak/modules,/opt/jboss/keycloak/modules/system/layers/keycloak,/opt/jboss/keycloak/modules/system/layers/base))]`

**Comment by TheSDTM** [comment]
Thank you, but now the container doesn't start. Here is the log https://pastebin.com/YqSLzgR1
Maybe because of the typo here?
![Снимок экрана 2021-03-22 в 09 41 33](https://user-images.githubusercontent.com/13622053/111950234-0de92000-8af3-11eb-87ff-01122ede3b50.png)

**Comment by vzakharchenko** [comment]
Hi @TheSDTM, You a right , i fixed this issue

**Comment by vzakharchenko** [comment]
Can you try again?

**Comment by TheSDTM** [comment]
Yes, thank you, now it works! Also, I got 'SUCCESS' with no realm specified.
