### ISSUE TITLE
radius.conf file not found under keycloak tree.

### ISSUE THREAD

**Issue by noci2012** [vzakharchenko/keycloak-radius-plugin#358]
**Describe the bug**
The plugin requires the config file to be: /config/radius.conf
instead of ${KEYCLOAK_PATH}/config/radius.conf

**To Reproduce**
Add plugins to existing keycloak and try to start ...

**Expected behavior**
Well that the file could be kept within the keycloak directory

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: CentOS V7.9
 - Browser: not relevant

**Smartphone (please complete the following information):**
Not relevant

**Additional context**

**Comment by vzakharchenko** [comment]
@noci2012 ,  plugin now supports keycloak KEYCLOAK_PATH variable, but you can override config file path with RADIUS_CONFIG_PATH

example:
```
export RADIUS_CONFIG_PATH=/opt/radius/config
```

**Comment by noci2012** [comment]
Thanks.
