### ISSUE TITLE
Update to keycloak 18.0.0?

### ISSUE THREAD

**Issue by noci2012** [vzakharchenko/keycloak-radius-plugin#589]
**Is your feature request related to a problem? Please describe.**
A new keycloak has been issued 

**Describe the solution you'd like**
Update your distribution of the combined kit?

**Describe alternatives you've considered**
N/A

**Additional context**
Are the delays caused by the situation in your country?

**Comment by vzakharchenko** [comment]
Hi @noci2012, yes the delay is caused by the war in my country.

**Comment by noci2012** [comment]
The software works as intended, thanks for the release.
