### ISSUE TITLE
Problems with the installation instructions?

### ISSUE THREAD

**Issue by danielcshn** [vzakharchenko/keycloak-radius-plugin#803]
**Describe the bug**
Problem when following the steps for the installation.

**To Reproduce**
1. Install Ubuntu Server 22.04.2 LTS.
2. Install keycloak-21.1.1.
3. wget https://github.com/vzakharchenko/keycloak-radius-plugin/releases/download/v1.4.11-21.0.0/keycloak-radius.zip
4. unzip keycloak-radius.zip -d keycloak-radius
5. cd keycloak-radius
6. sh bin/kc.sh --debug 8190 start-dev --http-port=8090

**Expected behavior**
Installation successful?

**Screenshots**
![image](https://github.com/vzakharchenko/keycloak-radius-plugin/assets/67213069/2e8f46f2-ff78-41dd-af79-29b651fed25d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-71-generic x86_64)
 - Browser Google Chrome
 - Version 113.0.5672.92 (64 bits)

**Comment by andrm** [comment]
Can you try to use "bash" instead of "sh" ?

**Comment by danielcshn** [comment]
Solved:

```txt
apt-get update -y
apt-get install default-jdk unzip -y
```

```txt
wget https://github.com/vzakharchenko/keycloak-radius-plugin/releases/download/v1.4.11-21.0.0/keycloak-radius.zip
unzip keycloak-radius.zip -d keycloak-radius
mv keycloak-radius /opt/keycloak
useradd -r -g keycloak -d /opt/keycloak -s /sbin/nologin keycloak
chown -R keycloak: /opt/keycloak
chmod o+x /opt/keycloak/bin/
mkdir /etc/keycloak
```

```txt
export KEYCLOAK_ADMIN=<USERNAME>
export KEYCLOAK_ADMIN_PASSWORD=<PASSWORD>
```

```txt
bin/kc.sh --debug 8190 start-dev --http-port=8090
```
